### ISSUE TITLE
PHP7 version of this package?

### ISSUE THREAD

**Issue by marksteele** [iuscommunity-pkg/php56u-pecl-amqp#1]
Any way to make this happen?

**Comment by marksteele** [comment]
In theory just a slight tweaking of https://github.com/remicollet/remirepo/blob/master/php/pecl/php-pecl-amqp/php-pecl-amqp.spec should do the trick

**Comment by carlwgeorge** [comment]
Howdy @marksteele,

Please submit a new package request for php70u-pecl-amqp on our [wishlist](https://github.com/iuscommunity/wishlist).
